"""empty message

Revision ID: e56b6be3c590
Revises: 8140441a9ba2
Create Date: 2018-02-24 20:33:02.558708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e56b6be3c590'
down_revision = '8140441a9ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('read_times', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'read_times')
    # ### end Alembic commands ###
